[project]
name = "cmake-lint-paddle"
version = "1.5.2"
description = "A fork of cmake-lint for PaddlePaddle"
readme = "README.md"
requires-python = ">=3.10"
authors = [
  { name = "Richard Quirk", email = "richard.quirk@gmail.com" },
  { name = "Nyakku Shigure", email = "sigure.qaq@gmail.com" },
]
keywords = ["cmake", "lint"]
license = { text = "Apache 2.0" }
classifiers = [
  "Environment :: Console",
  "Operating System :: OS Independent",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: Implementation :: CPython",
]
dependencies = []

[project.urls]
Homepage = "https://github.com/PFCCLab/cmake-lint-paddle"
Documentation = "https://github.com/PFCCLab/cmake-lint-paddle"

[project.scripts]
cmakelint = "cmakelint.__main__:main"

[dependency-groups]
dev = ["pytest>=8.4.2", "ruff>=0.14.0", "syrupy>=5.0.0"]

[tool.uv.build-backend]
module-name = "cmakelint"

[tool.ruff]
line-length = 120
target-version = "py310"

[tool.ruff.lint]
select = [
  # Pyflakes
  "F",
  # Pycodestyle
  "E",
  "W",
  # Isort
  "I",
  # Pyupgrade
  "UP",
  # Flake8-pyi
  "PYI",
  # Yesqa
  "RUF100",
]
ignore = [
  "E501", # line too long, duplicate with black
  "E731", # lambda sometimes is more readable
  "F841", # local variable is assigned to but never used, duplicate with pyright
]

[tool.ruff.lint.isort]
required-imports = ["from __future__ import annotations"]
known-first-party = ["cmakelint"]

[tool.pytest.ini_options]
python_files = ["tests/*.py", "tests/**/*.py"]

[build-system]
requires = ["uv_build>=0.9.0,<0.10.0"]
build-backend = "uv_build"
